name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '👋 Welcome! Thanks for opening your first issue here. We appreciate your contribution!'
          pr-message: '🎉 Thanks for your first pull request! We will review it soon. Welcome aboard! 🚀'